// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/flow/distribution/demographics": {
            "post": {
                "description": "Retorna a porcentagem e volume de público por Gênero e Classe Social",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demografia"
                ],
                "summary": "Distribuição demográfica",
                "parameters": [
                    {
                        "description": "Filtros de busca",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DemographicsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/flow/metrics": {
            "post": {
                "description": "Retorna o total de audiência e o fluxo de pessoas por hora (24h)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Métricas"
                ],
                "summary": "Obter métricas gerais",
                "parameters": [
                    {
                        "description": "Filtros de busca",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MetricsResponse"
                        }
                    },
                    "400": {
                        "description": "Filtros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno no servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/flow/ranking/neighborhoods": {
            "post": {
                "description": "Retorna o ranking das ruas utilizando geocodificação reversa para obter nomes reais",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ranking"
                ],
                "summary": "Ranking de ruas mais movimentadas",
                "parameters": [
                    {
                        "description": "Filtros de busca e limite",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.RankingResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/flow/spatial": {
            "post": {
                "description": "Retorna pontos de latitude/longitude com volume para o mapa de calor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fluxo"
                ],
                "summary": "Obter dados espaciais",
                "parameters": [
                    {
                        "description": "Filtros de busca",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.SpatialResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CategoryValue": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "models.DataRequest": {
            "type": "object",
            "required": [
                "filters"
            ],
            "properties": {
                "filters": {
                    "description": "Filters contém os critérios de busca (Idade, Gênero, Classe)\nO 'binding:\"required\"' avisa ao Gin que este campo não pode ser nulo",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.FilterPayload"
                        }
                    ]
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "models.DemographicsResponse": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CategoryValue"
                    }
                },
                "socialClass": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CategoryValue"
                    }
                }
            }
        },
        "models.FilterPayload": {
            "type": "object",
            "properties": {
                "ageGroups": {
                    "description": "Lista de faixas etárias (ex: [\"65\", \"23\", \"31\"])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "18-24",
                        "25-34"
                    ]
                },
                "genders": {
                    "description": "Lista de gêneros (ex: [\"M\", \"F\"])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Masculino"
                    ]
                },
                "socialClasses": {
                    "description": "Lista de classes sociais (ex: [\"A\", \"B1\", C1])",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "A",
                        "B"
                    ]
                }
            }
        },
        "models.HourCount": {
            "type": "object",
            "properties": {
                "hour": {
                    "type": "integer"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "models.MetricsResponse": {
            "type": "object",
            "properties": {
                "flow24h": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HourCount"
                    }
                },
                "totalAudience": {
                    "type": "integer"
                }
            }
        },
        "models.RankingResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "models.SpatialResponse": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "weighted_uniques": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Eletromidia Flow API",
	Description:      "API para dashboard de fluxo de audiência com BigQuery e Google Maps.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
