basePath: /api/v1
definitions:
  models.CategoryValue:
    properties:
      category:
        type: string
      percentage:
        type: number
      volume:
        type: integer
    type: object
  models.DataRequest:
    properties:
      filters:
        allOf:
        - $ref: '#/definitions/models.FilterPayload'
        description: |-
          Filters contém os critérios de busca (Idade, Gênero, Classe)
          O 'binding:"required"' avisa ao Gin que este campo não pode ser nulo
      limit:
        type: integer
    required:
    - filters
    type: object
  models.DemographicsResponse:
    properties:
      gender:
        items:
          $ref: '#/definitions/models.CategoryValue'
        type: array
      socialClass:
        items:
          $ref: '#/definitions/models.CategoryValue'
        type: array
    type: object
  models.FilterPayload:
    properties:
      ageGroups:
        description: 'Lista de faixas etárias (ex: ["65", "23", "31"])'
        example:
        - 18-24
        - 25-34
        items:
          type: string
        type: array
      genders:
        description: 'Lista de gêneros (ex: ["M", "F"])'
        example:
        - Masculino
        items:
          type: string
        type: array
      socialClasses:
        description: 'Lista de classes sociais (ex: ["A", "B1", C1])'
        example:
        - A
        - B
        items:
          type: string
        type: array
    type: object
  models.HourCount:
    properties:
      hour:
        type: integer
      volume:
        type: integer
    type: object
  models.MetricsResponse:
    properties:
      flow24h:
        items:
          $ref: '#/definitions/models.HourCount'
        type: array
      totalAudience:
        type: integer
    type: object
  models.RankingResponse:
    properties:
      name:
        type: string
      volume:
        type: integer
    type: object
  models.SpatialResponse:
    properties:
      latitude:
        type: number
      longitude:
        type: number
      weighted_uniques:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para dashboard de fluxo de audiência com BigQuery e Google Maps.
  title: Eletromidia Flow API
  version: "1.0"
paths:
  /flow/distribution/demographics:
    post:
      consumes:
      - application/json
      description: Retorna a porcentagem e volume de público por Gênero e Classe Social
      parameters:
      - description: Filtros de busca
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DemographicsResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Distribuição demográfica
      tags:
      - Demografia
  /flow/metrics:
    post:
      consumes:
      - application/json
      description: Retorna o total de audiência e o fluxo de pessoas por hora (24h)
      parameters:
      - description: Filtros de busca
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MetricsResponse'
        "400":
          description: Filtros inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno no servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obter métricas gerais
      tags:
      - Métricas
  /flow/ranking/neighborhoods:
    post:
      consumes:
      - application/json
      description: Retorna o ranking das ruas utilizando geocodificação reversa para
        obter nomes reais
      parameters:
      - description: Filtros de busca e limite
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/models.RankingResponse'
              type: array
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ranking de ruas mais movimentadas
      tags:
      - Ranking
  /flow/spatial:
    post:
      consumes:
      - application/json
      description: Retorna pontos de latitude/longitude com volume para o mapa de
        calor
      parameters:
      - description: Filtros de busca
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/models.SpatialResponse'
              type: array
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obter dados espaciais
      tags:
      - Fluxo
swagger: "2.0"
