stages:
  - test
  - build
  - deploy
  # more stages

include:
  - local: ".gitlab/ci/variables.yml"
  - local: ".gitlab/ci/actions-rules.yml"
  - local: ".gitlab/ci/branch-rules.yml"
  - local: ".gitlab/ci/pipeline-check.yml"
  - local: ".gitlab/ci/docs.yml"
  - local: ".gitlab/ci/release.yml"
  - local: ".gitlab/ci/sync-branches.yml"
  # more component pipelines
